"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { SchoolForm } from "@/components/super-admin/school-form"
import { useCreateTenant } from "@/lib/api/tenants"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { toast } from "sonner"

export default function NewSchoolPage() {
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()
  const createTenant = useCreateTenant()

  const handleSave = async (schoolData: any) => {
    setIsLoading(true)
    try {
      // Map school form data to tenant API format
      const tenantData = {
        name: schoolData.name || `${schoolData.subdomain} School District`,
        subdomain: schoolData.subdomain,
        domain: schoolData.subdomain ? `${schoolData.subdomain}.compasse.net` : undefined,
        school: {
          name: schoolData.name || "",
          address: schoolData.address || "",
          phone: schoolData.phone || "",
          email: schoolData.email || "",
          website: schoolData.subdomain ? `https://${schoolData.subdomain}.compasse.net` : undefined,
          admin_name: schoolData.principalName || "School Administrator",
          admin_email: schoolData.email ? `admin@${schoolData.subdomain}.compasse.net` : undefined,
          // Password will be auto-generated by backend if not provided
        },
        settings: {
          timezone: schoolData.settings?.timezone || "Africa/Lagos",
          currency: schoolData.settings?.currency || "NGN",
        },
      }

      const response = await createTenant.mutateAsync(tenantData)
      
      console.log("School created successfully!", response)
      
      // Get admin credentials from response (API can return it in different locations)
      const adminCredentials = response.admin_credentials || response.tenant?.admin_credentials
      const schoolName = response.school?.name || response.tenant?.name || "School"
      
      if (adminCredentials) {
        toast.success(`${schoolName} created successfully!`, {
          description: `Admin Email: ${adminCredentials.email}\nPassword: ${adminCredentials.password}`,
          duration: 12000,
        })
      } else {
        toast.success(`${schoolName} created successfully!`)
      }

      // Redirect to schools list page after showing toast
      // Delay allows user to see and copy the admin credentials
      setTimeout(() => {
        router.push("/super-admin/schools")
      }, 1500)
    } catch (error: any) {
      console.error("Error creating school:", error)
      const errorMessage = error?.response?.data?.message || error?.message || "Failed to create school"
      toast.error("Error creating school", {
        description: errorMessage,
      })
    } finally {
      setIsLoading(false)
    }
  }

  const handleCancel = () => {
    router.push("/super-admin/schools")
  }

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center space-x-4">
        <Link href="/super-admin/schools">
          <Button variant="outline" size="sm">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Schools
          </Button>
        </Link>
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Add New School</h1>
          <p className="text-gray-600 mt-1">Create a new school in the system</p>
        </div>
      </div>

      <div className="max-w-4xl">
        <SchoolForm onSave={handleSave} onCancel={handleCancel} isLoading={isLoading} />
      </div>
    </div>
  )
}
